![image.png](attachment:image.png)
# NumPy

NumPy ( Numerical Python )는 거의 모든 과학 및 공학 분야에서 사용되는 오픈 소스 파이썬 라이브러리로써, NumPy API는 Pandas, SciPy, Matplotlib, scikit-learn, scikit-image 및 대부분의 기타 데이터 과학 및 과학 파이썬 패키지에서 광범위하게 사용됨

# ⏣ 설치

In [1]:
!pip install numpy

# ⏣ 임포트

In [39]:
import numpy as np

# ⏣ 기본 배열 만들기
numpy 배열(numpy.ndarray)을 만들기 위한 함수 : np.array(), np.zeros(), np.ones(), np.arange(), np.linspace()   
numpy 배열(numpy.ndarray) 요소(element)의 자료형 지정 및 확인 : dtype   

### 1. np.array()

In [5]:
a = np.array ([1,2,3])
type(a)

numpy.ndarray

In [6]:
a

array(['1', '2', '3'], dtype='<U21')

### 2. np.zeros()

In [9]:
b=np.zeros([2,2])

In [10]:
b


array([[0., 0.],
       [0., 0.]])

### 3. np.ones()

In [21]:
a=np.ones([2,2])

In [22]:
a

array([[1., 1.],
       [1., 1.]])

### 4. np.empty()

In [23]:
a=np.empty([2,2])

In [24]:
a # (n,m)

array([[1., 1.],
       [1., 1.]])

In [ ]:
np.array([1,2,3])

In [ ]:
# empty함수는 초기화되지 않은 배열을 생성한다. 따라서 메모리의 상태에 따라서 다른 값이 나올 수 있다.

### 5. np.arange()

In [26]:
a=np.arange(1,10) # 범위 [start, stop)

In [27]:
# 범위내 증가치 적용
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
range(2,12,3)  # 파이썬의 range함수는 값이 아닌 range 객체를 반환한다.

range(2, 12, 3)

In [31]:
a=range(2,12,3)

### 6. np.linspace()

In [36]:
# 범위 [start, stop]
a=np.linspace[1,10]

TypeError: ignored

In [ ]:
# num 인자 사용


In [ ]:
# num의 기본값은 50이다.


### 7. dtype

In [12]:
a = np.array =([1,2,3])
a

[1, 2, 3]

In [11]:
b = np.array([1,2,3], dtype=np.uint64) 
b

array([1, 2, 3], dtype=uint64)

AttributeError: ignored

In [14]:
b.dtype

dtype('uint64')

# ⏣ 배열 요소의 추가, 제거, 정렬 및 배열 합치기
numpy 배열(numpy.ndarray) 요소(element)의 추가, 제거, 정렬 : np.append(), np.delete(), np.sort()   
numpy 배열(numpy.ndarray) 합치기 : np.concatenate()   

### 1. np.append()

In [3]:
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [ ]:
# 배열의 끝에 값이 추가됨


In [ ]:
# 배열 arr 자체가 바뀌지는 않음


In [ ]:
# 배열이 평탄화(flatten)된 후 추가됨 == 배열의 축이 없어짐 axis=None


In [ ]:
arr1 = 
arr1

In [ ]:
# axis=0


In [ ]:
# axis=1
# 튜플로 추가한 경우


In [ ]:
# 축의 방향과 배열의 shape가 맞지 않아 오류 발생


In [ ]:
# 배열로 추가한 경우, 배열의 shape을 맞춰줘야 한다.


### 2. np.delete()

In [ ]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# 인덱스가 1, 3, 5인 배열의 요소 삭제


### 3. np.sort()

In [4]:
arr = np.array([2,5,3,2,1,6,7,8])
arr

array([2, 5, 3, 2, 1, 6, 7, 8])

In [5]:
np.sort(arr)

array([1, 2, 2, 3, 5, 6, 7, 8])

In [8]:
np.sort(arr,axis=0) #axis=0 세로방향 1,3을 비교 2,4를 비교 후 정렬

array([[1, 2],
       [3, 4]])

In [9]:
np.sort(arr,axis=1) #axis=1 가로방향 1,4를 비교 3,2를 비교 후 정렬

array([[1, 4],
       [2, 3]])

### 4. np.concatenate()

In [14]:
a = np.array([[1,2],[3,4]]) #(2,2)
b = np.array([[5,6]])   #(1,2)
a,b

(array([[1, 2],
        [3, 4]]), array([[5, 6]]))

In [15]:
np.concatenate ((a,b) ,axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [17]:
np.concatenate ((a,b.T) ,axis=1) #b :(1,2) --> (2,1) => (2,3)

array([[1, 2, 5],
       [3, 4, 6]])

# ⏣ 배열의 모양(shape)과 크기(size)
배열의 차원 또는 축의 수 : ndarray.ndim   
배열 요소의 총 개수 : ndarray.size   
배열의 차원에 따라 저장된 요소의 수 : ndarray.shape

NameError: ignored

In [ ]:
# 축의 수

In [ ]:
# 모든 요소의 수

In [ ]:
# 축 별 요소의 수

# ⏣ 배열의 인덱싱(indexing)과 슬라이싱(slicing)

In [23]:
data = np.array([1,2,3])

In [24]:
data[1] # 인덱싱 == 값

2

In [28]:
data[1:2] # 슬라이싱  == 배열

array([2])

In [31]:
data[-3:2]

array([1, 2])

In [32]:
a = np.array ([[1,2,3,4] ,[5,6,7,8] ,[9,10,11,12]]) 
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [34]:
five_up = (a>5)
five_up

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [35]:
a[five_up]

array([ 6,  7,  8,  9, 10, 11, 12])

In [40]:
a[(a>5) & (a<10)]

array([6, 7, 8, 9])

# ⏣ 행렬(2D 배열)의 인덱싱(indexing)에서 주의할 점
### [ , ] vs. [ ][ ]

In [43]:
mat = np.arange(24).reshape(6,4)
mat

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [44]:
mat[1:5 ,0:2] # row, col로 인식하고 슬라이싱

array([[ 4,  5],
       [ 8,  9],
       [12, 13],
       [16, 17]])

In [45]:
mat [1:5][0:2]# row로 슬라이싱한 결과를 다시 row로 슬라이싱

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# ⏣ 행렬(2D 배열)의 전치(transpose) 및 재구성(reshape)

행렬의 전치 : arr.transpose(), arr.T   
행렬의 재구성 : arr.reshape()   


In [ ]:
arr = 
arr

In [ ]:
data = 
data

In [ ]:
new_arr = 
new_arr

In [ ]:
# data.shape = (6,)와 비교

# ⏣ 배열 평탄화

배열 평탄화 : ndarray.flatten(), ndarray.ravel()

In [ ]:
x = 
x

In [ ]:
# ndarray.flatten()은 원래 배열의 사본을 반환


In [ ]:
# ndarray.ravel()은 원래 배열의 뷰(view)를 반환. 뷰를 수정하면 원본도 수정된다.


# ⏣ 기본 배열 연산 : 사칙연산

In [51]:
data = np.array([1,2])
ones = np.ones([2])


SyntaxError: ignored

In [49]:
data+ones

array([2., 3.])

# ⏣ 브로드캐스팅(Broadcasting)

In [53]:
data *1.2

array([1.2, 2.4])

# ⏣ 유용한 배열 연산들
maximum, minimum, sum, mean, product, standard deviation 등등

In [57]:
import random

In [59]:
a = np.random.random_sapmle((3,4))
a

AttributeError: ignored

# ⏣ 저장, 로딩

저장 : np.save(), np.savetxt     
로딩 : np.load(), np.loadtxt

In [61]:
a = np.array([1,2,3,4,5] , dtype=np.int64)
a

array([1, 2, 3, 4, 5])

In [ ]:
# 단일 ndarray 객체를 저장 : filename.npz로 저장
np.save('np_save' , a)
!dir

In [66]:
# numpy.ndarray 객체를 저장한 filename.npy를 로딩하여 변수에 저장
b=np.load('np_save.npy')
b.dtype

dtype('int64')

In [69]:
# numpy.ndarray 객체를 텍스트 파일로 저장
np.savetxt('new.file.csv',a)
!dir

new.file.csv  np_save.npy  sample_data


In [71]:
b= np.loadtxt('new.file.csv') # 텍스트 파일의 데이터 로딩
b.dtype

dtype('float64')

# 참고문헌

https://numpy.org/doc/stable/user/absolute_beginners.html